config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#homepage'
  resources :user_sessions
  resources :users, only: [:index, :new, :create]
  resources :plants do
    member do
      get 'send_moisture_reading'
      patch 'send_moisture_reading' => 'plants#update_moisture_reading'
    end
  end
  get 'pages/homepage'
  get 'login' => 'user_sessions#new', :as => :login
  get 'signup' => 'users#new', :as => :signup
  get 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/plant.rb
class Plant < ActiveRecord::Base
  belongs_to :user

  def needs_watering? 
    if sensor_moisture > moisture_threshold 
      # user.send_alert_email
      return true  
    else 
      return false  
    end
  end

  def sensor_moisture
    # TODO
    @moisture ||= rand(100..300) 
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3}
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
  has_many :plants

  def send_alert_email
    UserMailer.send_alert(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def homepage
    @user = User.new
    render 'user_sessions/new'
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  
  def index
    @plants = current_user.plants

  end
  
  def show
    @plant = Plant.find(params[:id])    
  end
  
  def new
    @plant = Plant.new
  end

  def edit
    @plant = Plant.find(params[:id])
  end

  def create
    @plant = Plant.new(plant_params)
    @plant.user = current_user
      if @plant.save
        redirect_to plants_url
      else
        render :new 
      end   
  end

  def update
    @plant = Plant.find(params[:id])
    if @plant.update_attributes(plant_params)
      redirect_to plant_path(@plant)
    else 
      render :edit
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy 
    redirect_to plants_path 
  end

  def update_moisture_reading
    @plant = Plant.find(params[:id])
    if @plant.update_attributes(moisture_reading)
      redirect_to plant_path(@plant)
    else 
      render :send_moisture_reading
    end
  end

  def send_moisture_reading
    @plant = Plant.find(params[:id])
    @plant.update_attributes(moisture_reading)
    @plant.update_attributes({last_moisture_reading_at: DateTime.now}) 
  end

  private

  def plant_params 
    params.require(:plant).permit(:plant_name, :description, :notes)
  end 

  def moisture_reading 
    params.permit(:moisture_reading)
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:plants)
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to plants_url, notice: "Signed up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gnomely</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

  <div>
   <p id="notice"><%= flash[:notice] %></p>
   <p id="alert"><%= flash[:alert] %></p>
 </div>

<%= yield %>

</body>
</html>

app/views/pages/homepage.html.erb
<html>
  <head>
    <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <style>
    body {
      font-family: 'Lobster', cursive;
      font-size: 48px;
      text-shadow: 4px 4px 4px #aaa;
    }
    </style>
  </head>
  <body>
    <h1>Helping the lazy urban gardener since 2015.</h1>
    <div class="logo">
      <%= image_tag 'Gnomely-logo.png' %>
    </div>
  <%= yield %>
  </body>
</html>

app/views/plants/_form.html.erb
  <div class="background"></div>
<%= form_for(@plant) do |f| %>
  <div class="field">
    <%= f.label :plant_name %><br />
    <%= f.text_field :plant_name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :moisture_threshold %><br />
    <%= f.number_field :moisture_threshold %>
  </div>
  <div class="field">
    <%= f.label :temp_threshold %><br />
    <%= f.number_field :temp_threshold %>
  </div>
  <div class="field">
    <%= f.label :sensor_id %><br />
    <%= f.number_field :sensor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plants/_plant.html.erb
<div class="plant <%= plant.needs_watering? ? "red": "green"%>">
  <h1><%= link_to plant.plant_name, plant %></h1>
  <% if plant.needs_watering?  %>
    <p>Plant needs watering </p>
  <% else %>
    <p>Plant is hydrated</p>
  <% end %>
</div>
  

app/views/plants/edit.html.erb
<div id="nav">
      <%= link_to "Back to Plant", @plant %>  |
      <%= link_to "My Plants", plants_path %> |
      <%= link_to "Logout", logout_path %>
</div>
<h1>Edit Plant</h1>

<%= render 'form' %>

app/views/plants/index.html.erb
<div id="nav">
      <%= link_to "Add New Plant", new_plant_path %> |
      <%= link_to "My Plants", plants_path %> |
      <%= link_to "Logout", logout_path %>
</div>

<div class="background"></div>
<h1>My Plants</h1>
<div id="plants">
  <%= render @plants %>
</div>

app/views/plants/new.html.erb
<div id="nav">
      <%= link_to "My Plants", plants_path %> |
      <%= link_to "Logout", logout_path %>
</div>
<h1>Add Plant</h1>

<%= render 'form' %>

app/views/plants/send_moisture_reading.html.erb
<h1>Sending moisture reading</h1>
<%= form_tag(send_moisture_reading_plant_path(@plant), method: :PATCH) do %>
<div class="field">
    <%= label_tag :moisture_reading %><br />
    <%= number_field_tag :moisture_reading, @plant.moisture_reading%>
</div>
<div class="actions">
  <%= submit_tag %>
</div>
<% end %>

app/views/plants/show.html.erb
<div id="nav">
      <%= link_to "Edit", edit_plant_path(@plant) %>  |
      <%= link_to "Delete", @plant, method: "delete", data: {confirm: "Are you sure you want to delete this plant?"} %> |
      <%= link_to "My Plants", plants_path %> |
      <%= link_to "Logout", logout_path %>
</div>
<div class="background"></div>

<h1><%= @plant.plant_name %></h1>
<div id="plant_image">
  <%= image_tag @plant.url %>
</div>  
<div class="plant_info">
  <h2>Plant Description</h2>
  <p><%= @plant.description %></p>
  <h2>Moisture Threshold</h2>
  <p><%= @plant.moisture_threshold %></p>
  <h2>Notes</h2>
  <p><%= @plant.notes %></p>
</div>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br/>
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br/>
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<head>
    <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <style>
    
    </style>
</head>
<body>
    <h1>Helping the lazy urban gardener since 2015.</h1>
    <div id="login">
      <div class="logo">
        <%= image_tag 'Gnomely-logo.png' %>
      </div>
      <div id="tabs">
        <ul>
          <li><a href="#login"><span>Login</span></a></li>
          <li><a href="#signup"><span>Sign Up</span></a></li>
        </ul>
        <div id="login">
          <%= render :partial => 'user_sessions/form' %>
        </div>
        <div id="signup">
          <%= render :partial => 'users/form' %>
        </div>
     </div>

      <script>
        $( "#tabs" ).tabs();
      </script>
    </div>
  <%= yield %>
  </body>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<div id="register-form">
  <h1>Sign Up</h1>
  <%= render 'form' %>
</div>